List<String> question = [
  "Kualitas hidup memerlukan fondasi berupa mental yang sehat.",
  "Kesehatan mental ditandai dengan penyesuaian diri yang baik.",
  "Kesehatan mental ditandai dengan kemampuan mengatasi stres sehari-hari.",
  "Dalam kadar tertentu, stres dibutuhkan untuk keluar dari zona nyaman.",
  "Gangguan mental adalah hal yang normal.",
  "Gangguan mental adalah hal yang misterius.",
  "Gangguan mental mengandung nilai estetik.",
  "Diagnosis gangguan mental tergantung persepsi dari masing-masing individu.",
  "Individu sendirilah yang paling memahami perasaan dan perilakunya.",
  "Perasaan sedih, cemas, dan tertekan yang bersifat situasional tidak berbeda dengan diagnosis gangguan mental.",
  "Gangguan bipolar merupakan hal yang trendi.",
  "Depresi merupakan indikasi seseorang dengan kemampuan intelektual yang tinggi.",
  "Anoreksia merupakan indikasi seseorang mampu mengontrol pola dietnya.",
  "Ketika melakukan diagnosis diri, individu cenderung memilih diagnosis yang sesuai dengan harapannya.",
  "Diagnosis gangguan  mental yang diberikan oleh para ahli pasti akurat.",
  "Romantisasi gangguan mental dapat mendorong pengabaian terhadap keseriusan gangguan mental.",
  "Romantisasi gangguan mental dapat menjadi justifikasi atas perilaku mengganggu diri sendiri dan orang lain.",
  "Romantisasi gangguan mental dapat memicu kesalahan diagnosis terhadap diri sendiri.",
  "Gangguan mental dapat disembuhkan dengan cara “self-healing”.",
  "Gangguan mental dapat disembuhkan dengan cara “self-love”.",
];
